### ISSUE TITLE
Plan for releasing the project as a Python library

### ISSUE THREAD

**Issue by skytin1004** [Imperial-EE-Microsoft/co_op_translator#12]
I have drafted a plan for releasing the project as a Python library on PyPI. The steps are outlined below. I'd like to discuss this plan and get feedback before proceeding with the release:

1. **Prepare project structure**:
   - Ensure the project structure follows the standard for Python package distribution, with a clear directory for the library, tests, and necessary documentation.
   - Include a `pyproject.toml` file to specify project metadata, dependencies, and build instructions.

2. **Set up configuration**:
   - Define project metadata in `pyproject.toml` .
   - Include necessary dependencies and version information.

3. **Build the package**:
   - Use `setuptools` and `wheel` to build the package.
   - Run the following command:
     ```bash
     python -m build
     ```
   - The build will generate `.tar.gz` and `.whl` files in the `dist/` folder.

4. **Create PyPI account and generate API token**:
   - Create a PyPI account if you haven’t done so.
   - Generate an API token to upload the package.

5. **Upload the package to PyPI**:
   - Install `twine` and upload the package:
     ```bash
     pip install --upgrade twine
     twine upload dist/*
     ```

6. **Test the package**:
   - After uploading, test the library by installing it using:
     ```bash
     pip install your_project
     ```

7. **Update the README**:
   - Update the README file to reflect the new installation and usage instructions based on the released library.

---

@timothycdc I'd appreciate feedback on any suggestions or additional steps you think we should include before proceeding with the PyPI release.

> [!NOTE]
>
> I plan to proceed with the PyPI release once issue #7 is resolved.

**Comment by skytin1004** [comment]
@timothycdc What do you think about changing the repository and project name to the original name, "**co_op_translator**," before the release?

**Comment by skytin1004** [comment]
@timothycdc Since we're preparing to release the project as a Python library, we'll need to adopt a license. I think the **MIT license** would be a good choice. What are your thoughts on that?

**Comment by timothycdc** [comment]
Hey @skytin1004 , MIT license is fine.

Yes, it's good to change the repository and project name to reflect that it's a Python package and not just notebooks.

Do you have access to changing the repo name? I could help you do it when https://github.com/Imperial-EE-Microsoft/microsoft_translation_public/issues/7 is resolved.

**Comment by skytin1004** [comment]
@timothycdc As for changing the repository and project name, I can do it myself since I have owner permissions. Thanks for letting me know!

As for #7, it seems that modifying the prompt alone is working well. I’ve tested it about 10 times, and it performs consistently, so I think we can consider this later.

**Comment by skytin1004** [comment]
@timothycdc And if you sign up for PyPI later, could you please let me know your account name and email so I can add you to the authors list
