### ISSUE TITLE
Arabic,  Urdu language characters displaying incorrectly

### ISSUE THREAD

**Issue by skytin1004** [Imperial-EE-Microsoft/co_op_translator#19]
When translating content into **Arabic**, certain characters are not rendering correctly and appear corrupted or broken. This issue occurs in some parts of the translated text, leading to readability problems. Currently, the font being used is `NotoSansArabic-Medium.ttf`, but considering switching to another font to address the issue.

> Similarly, the same issue is happening with the language “Urdu” using “NotoSansArabic-Medium.ttf”. In particular, English proper nouns like Phi-3 and Github seem to break when imported verbatim, so we should check if “NotoSansArabic-Medium.ttf” supports English as well.

![phi3small 1c844082966d3ea3b792c45285a98b6a8eaa1d699f1d61a16d5da0b5348d2756 ar](https://github.com/user-attachments/assets/3066a913-b658-45d0-8fca-e65656840fba)
![phi3medium 2acbb543db371485972e55e64930459c9d6077e62fd0ba637455e104c74c63f1 ar](https://github.com/user-attachments/assets/3ec00142-569a-49ff-a372-704cf1df4e18)
![phi3hardware 3098f4a73889a50098b43b99c5612d3d30d445233019fb2ac7fc1657cdacdb58 ar](https://github.com/user-attachments/assets/93b1802a-8a93-4d38-9eb3-0aa06c058562)
![Phi3getstarted def4a04395ec9eb07a089450fcc1622915f8e70cfef0bdb590450997739e26c6 ar](https://github.com/user-attachments/assets/b6e30e25-b5d4-44f5-abf8-ca51c2b22c33)
![phi3vision 88398b508ce20ff92fb05b07a3dd3f057335813ada361cc45a01755a74778208 ar](https://github.com/user-attachments/assets/f146a8af-f8b7-48bd-bbcc-4e4b2b003064)

**Comment by leestott** [comment]
Closing issue as we have migrated to a Microsoft Repo
