### ISSUE TITLE
Failed Translation from Chinese to Spanish with Missing Content

### ISSUE THREAD

**Issue by skytin1004** [Imperial-EE-Microsoft/co_op_translator#25]
# Issue: Failed Translation from Chinese to Spanish with Missing Content

When attempting to translate markdown documents from Chinese to Spanish, the translation fails entirely. In some cases, not even the disclaimer is shown. This seems to be happening due to the system using only the font of the target language, without processing the content correctly.

Example of original content in Chinese:

```markdown
# 变更日志

所有 "phi3ext" 扩展的显著更改都将记录在此文件中。

请查看 [保持变更日志](http://keepachangelog.com/) 以获取有关如何构建此文件的建议。

## [未发布]

- 初始版本


Expected translation (into Spanish) should have more than just the disclaimer at the end, but sometimes the output contains only the disclaimer text, such as:

```markdown
Aviso legal: La traducción fue realizada a partir de su original por un modelo de IA y puede no ser perfecta. 
Por favor, revise el resultado y haga las correcciones necesarias.
```

### Solution:
- Add a feature: Scan the files after translation to detect if the file is either empty or contains only the disclaimer text. If this happens, flag the file as "translation failed" and mark it in the progress bar for retrying later.
- Handle translation errors: If Azure OpenAI (AOAI) provides an invalid response or the translation fails, ensure that the translation process does not save an empty or disclaimer-only file, and instead, report the failure in the logs or UI for further action.

**Comment by leestott** [comment]
Closing issue as we have migrated to a Microsoft Repo
