### ISSUE TITLE
Skip custom markdown syntax like `[!NOTE]` during translation

### ISSUE THREAD

**Issue by skytin1004** [Imperial-EE-Microsoft/co_op_translator#7]
Currently, the translation process translates custom Markdown syntax like [!NOTE], which is intended for highlighting important information or notes in technical documents. These blocks should not be translated. For example:

```
> [!NOTA]
> Los modelos Phi-3 no tienen un rendimiento tan bueno...
In cases like the above, custom Markdown blocks such as [!NOTE], [!WARNING], etc., should be excluded from translation.
```

**Solution:**
Implement logic to detect and skip `[!NOTE]`, `[!WARNING]`, and similar custom blocks during the translation process.

**Comment by timothycdc** [comment]
Thanks for noticing this, we didn’t really test the code with GitHub flavoured markdown. One possible way to fix this could be at the prompting stage with the LLM call, but if you can somehow regex/skip/replace, that could probably be more reliable

**Comment by skytin1004** [comment]
Thanks, @timothycdc ! I agree that using regex to detect and preserve custom markdown blocks like [!NOTE] or [!WARNING] might be a more reliable approach.

I’ll try both approaches: handling it at the prompting stage with the LLM, and using regex to skip the custom markdown blocks. If both are feasible, I'll likely go with the regex method for reliability
